-- LOCAL/REVIEW ONLY. Do not run against production without explicit approval.
-- Existing application data is not altered by this migration.
create table if not exists public.cms_content (
  id bigint generated by default as identity primary key,
  content_type text not null,
  slug text not null,
  payload jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cms_content_type_slug_unique unique (content_type, slug)
);

create index if not exists cms_content_type_order_idx
  on public.cms_content (content_type, enabled, display_order);

create table if not exists public.cms_media (
  id bigint generated by default as identity primary key,
  bucket text not null,
  object_path text not null unique,
  public_url text not null,
  original_name text not null,
  mime_type text not null,
  byte_size bigint not null,
  created_at timestamptz not null default now()
);

create index if not exists cms_media_created_at_idx
  on public.cms_media (created_at desc);

create or replace function public.set_cms_content_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cms_content_updated_at on public.cms_content;
create trigger cms_content_updated_at
before update on public.cms_content
for each row execute function public.set_cms_content_updated_at();

-- Apply an RLS policy appropriate to the service-role-backed API only after
-- reviewing the project's existing Supabase policies. This migration does not
-- enable or alter RLS automatically.
